# Generated by Django 4.2.16 on 2024-09-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('size', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='MoodEntry',
        ),
    ]
